name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0 # Update to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0 # Update to the latest version
        with:
          node-version: 20 # Use the numeric version without quotes

      - name: Install dependencies
        run: npm install

      - name: Create assets directory
        run: mkdir -p android/app/src/main/assets

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        run: fastlane ios beta
